# Generated by Django 2.0.1 on 2018-01-21 14:38

import admin_email_sender.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_email_sender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template Name', max_length=50, verbose_name='Template Name')),
                ('html', models.TextField(default='\n<body>\n    @body\n</body>\n', help_text='You can use tags: <br>@body - <b>required</b><br>@username, @fullName, @firstName, @lastName', validators=[admin_email_sender.validators.validate_tags], verbose_name='HTML')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sendemail',
            name='text',
            field=models.TextField(help_text='You can use tags:<br>@username<br>@fullName<br>@firstName<br>@lastName'),
        ),
        migrations.AddField(
            model_name='sendemail',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_email_sender.Template'),
        ),
    ]
